import "~/styles/globals.css";

import { Manrope } from "next/font/google";
import { type Metadata } from "next";
import { Header } from "~/components/header";

export const metadata: Metadata = {
  title: "Audiophile",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const manrope = Manrope({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={manrope.className}>
      <body>
        <Header />
        <main>{children}</main>
        <div></div>
      </body>
    </html>
  );
}
