name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  playwright:
    name: "Playwright Tests"
    runs-on: ubuntu-latest
    env:
      POSTGRES_URL: ${{ vars.POSTGRES_URL }}
      POSTGRES_PRISMA_URL: ${{ vars.POSTGRES_PRISMA_URL }}
      POSTGRES_URL_NO_SSL: ${{ vars.POSTGRES_URL_NO_SSL }}
      POSTGRES_URL_NON_POOLING: ${{ vars.POSTGRES_NON_POOLING }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
    container:
      image: mcr.microsoft.com/playwright:v1.45.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js
        run: pnpm run build

      - name: Run the tests
        run: npx playwright test
        env:
          HOME: /root

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
